### ISSUE TITLE
movement issue

### ISSUE THREAD

**Issue by nu-fd2** [Zku11y/Yippee_Game#1]
<- (sahm lisr)   ^ (sahm lfo9)   ->(sahm limn)        mzyanin but     v (sahm lt7rt)      ma5damax

**Comment by Zku11y** [comment]
kys :3

**Comment by nu-fd2** [comment]
kys asshole 😡

![Lain Iwakura - 玲音 (Serial Experiments Lain - シリアルエクスペリメンツレイン) PonyXL  - Lain PonyXL _ Stable Diffusion LoRA _ Civitai](https://github.com/user-attachments/assets/65470aed-c6d4-4bd5-9515-586378bfe8f0)
